<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>5daee532-4fd2-4225-9a83-c3afb0152142</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'ลงทะเบียน')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.register-btn.btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aafdbc63-aeda-4698-9325-bdbd9715b3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>register-btn btn</value>
      <webElementGuid>5c397ec1-0123-406e-9407-5cfa8832ae48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/auth/login/common-oauth2-backend/</value>
      <webElementGuid>56f4a979-4bd8-4cb1-9267-74ceac5d9f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ลงทะเบียน</value>
      <webElementGuid>dd1f9813-1c1b-43e5-b254-c57cd4823e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ltr  lang_th&quot;]/div[@class=&quot;window-wrap&quot;]/header[@class=&quot;global-header&quot;]/div[@class=&quot;main-header&quot;]/nav[@class=&quot;nav-links&quot;]/div[@class=&quot;secondary&quot;]/div[1]/div[@class=&quot;mobile-nav-item hidden-mobile nav-item&quot;]/a[@class=&quot;register-btn btn&quot;]</value>
      <webElementGuid>74613035-8a57-45fa-972a-35f4df352a56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ลงทะเบียน')]</value>
      <webElementGuid>612362a1-73bc-404c-aebf-c883c1f1777d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore courses'])[1]/following::a[1]</value>
      <webElementGuid>b8dc9ab7-161f-427e-b8d9-8b7164e3b5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ข้ามไปที่เนื้อหาหลัก'])[1]/following::a[3]</value>
      <webElementGuid>9b400f04-0f3f-4d26-8d1c-cd987b856cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เข้าสู่ระบบ'])[1]/preceding::a[1]</value>
      <webElementGuid>2def75ea-ea95-4585-9d61-bdcb3224ec61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore courses'])[2]/preceding::a[2]</value>
      <webElementGuid>d5eba0a4-431a-41b2-a426-648af92f8704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ลงทะเบียน']/parent::*</value>
      <webElementGuid>81f90f04-3de0-4c2c-8c3f-276df024246c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/auth/login/common-oauth2-backend/')]</value>
      <webElementGuid>ea76b7fc-6308-4ac1-a487-58da30933920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>2efbab0a-e91a-40e9-8bdd-bc585f309aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/auth/login/common-oauth2-backend/' and (text() = 'ลงทะเบียน' or . = 'ลงทะเบียน')]</value>
      <webElementGuid>2a8f9840-1ed5-441b-ba7d-8effe40802c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
