<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Register</name>
   <tag></tag>
   <elementGuidId>9fb49948-4e13-4a77-90e6-32af1deded77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kc-registration']/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kc-registration > span > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f4dd8486-11bb-49a4-a000-a4aa81fb0756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>31bf67a4-e05c-451c-a72f-fe174fca1f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/auth/realms/thaimooc/login-actions/registration?client_id=edx&amp;tab_id=78IdQcMJ1a4</value>
      <webElementGuid>829a55d4-c18d-4861-8c0e-f4cc9e4fa941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>1713a2f9-8dd9-44fe-b05a-65db8d0b8b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kc-registration&quot;)/span[1]/a[1]</value>
      <webElementGuid>8b697121-125e-4597-8d41-f4e25ccf38b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kc-registration']/span/a</value>
      <webElementGuid>41cc06ab-d621-42d4-95fa-b3f56a228455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Register')]</value>
      <webElementGuid>4c99c59e-c33d-40be-b387-7c243096a113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password'])[1]/following::a[1]</value>
      <webElementGuid>85131e14-9a67-4f1f-8bfb-29ee7f6d0fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in with your Orgainzation'])[1]/preceding::a[1]</value>
      <webElementGuid>e3854a30-b6ec-4c64-acfb-ec0dc57cd367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Register']/parent::*</value>
      <webElementGuid>ccf915ba-8395-4f2e-bef3-304e9cf48472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/auth/realms/thaimooc/login-actions/registration?client_id=edx&amp;tab_id=78IdQcMJ1a4')]</value>
      <webElementGuid>c3ec3b65-b6d5-49e2-8733-3fc35551226f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span/a</value>
      <webElementGuid>d1680681-5b69-414e-bc62-0252d38c2142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/auth/realms/thaimooc/login-actions/registration?client_id=edx&amp;tab_id=78IdQcMJ1a4' and (text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>2a7aab4b-9a25-48dd-8a58-f413ff750196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/auth/realms/thaimooc/login-actions/registration?client_id=edx&amp;tab_id=UTT1kk_Lb0Q')]</value>
      <webElementGuid>b4426a2a-12f2-4c2f-bc2b-1424ccd13735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/auth/realms/thaimooc/login-actions/registration?client_id=edx&amp;tab_id=UTT1kk_Lb0Q' and (text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>41f0b097-6fa3-49a7-9507-077099f675f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/auth/realms/thaimooc/login-actions/registration?client_id=edx&amp;tab_id=FqbXx65dD4Y')]</value>
      <webElementGuid>95fdea1b-8d67-4a7d-8bc6-4038e34dba07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/auth/realms/thaimooc/login-actions/registration?client_id=edx&amp;tab_id=FqbXx65dD4Y' and (text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>2a3debe1-95a2-4e45-b177-781fa5feb5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/auth/realms/thaimooc/login-actions/registration?client_id=edx&amp;tab_id=P-qPKFs4lHM')]</value>
      <webElementGuid>0cad7f3a-efe6-4b14-ac68-e1c7993c62db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/auth/realms/thaimooc/login-actions/registration?client_id=edx&amp;tab_id=P-qPKFs4lHM' and (text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>b37ef480-8e1d-4026-be47-9b5c313ed899</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
